spring:
  application:
    name: Fleeting-time-v2
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/fleeting_time
    username: raitocc
    password: WTZor9EQYQpUS2Y4
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-cn-9me4964qo001148o.rwlb.rds.aliyuncs.com:3306/fleeting-time
#    username: root
#    password: H2v4uZwDpBVv4ysHy5wy
#    driver-class-name: com.mysql.cj.jdbc.Driver

# 服务器配置
server:
  address: 127.0.0.1   # 确保只监听本地回环地址
  port: 8081           # 将 Spring Boot 应用的监听端口改为 8081 (HTTP)

jwt:
  secret: YourSuperSecretKeyForJwtMustBeLongEnough123!
  duration: 1440

baidu:
  map:
    ak: cX3Lu6F9cEcRr7M2K80G0Di49wvz4hY0

logging:
  file:
    name: logs/fleeting-time.log # 主日志文件路径
  level:
    root: INFO
    org.whu.fleetingtime: DEBUG # 如果你想让自己项目下的日志更详细
#    org.springframework.jdbc.support.JdbcTransactionManager: debug # 事务管理debug信息开关

#Sms
sms:
  host: https://gyytz.market.alicloudapi.com
  path: /sms/smsSend
  method: POST
  appcode: 37d5da8d351c43fea103145f51e4d64c
  smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
  templateId: 908e94ccf08b4476ba6c876d13f084ad
#redis
redis:
  host: localhost
  port: 6379
  password:
  database: 0
