spring:
  application:
    name: Fleeting-time
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/fleeting_time
    username: raitocc
    password: WTZor9EQYQpUS2Y4
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis log out
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secret: YourSuperSecretKeyForJwtMustBeLongEnough123!
  duration: 30