spring:
  application:
    name: Fleeting-time
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/fleeting_time
    username: raitocc
    password: WTZor9EQYQpUS2Y4
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 512MB

# 服务器配置
server:
  address: 127.0.0.1   # 确保只监听本地回环地址
  port: 8081           # 将 Spring Boot 应用的监听端口改为 8081 (HTTP)

# mybatis log out
mybatis:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

jwt:
  secret: YourSuperSecretKeyForJwtMustBeLongEnough123!
  duration: 1440

baidu:
  map:
    ak: cX3Lu6F9cEcRr7M2K80G0Di49wvz4hY0

logging:
  file:
    name: logs/fleeting-time.log # 主日志文件路径
  level:
    root: INFO
    org.whu.fleetingtime: DEBUG # 如果你想让自己项目下的日志更详细
#    org.springframework.jdbc.support.JdbcTransactionManager: debug # 事务管理debug信息开关
